### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by ignacy** [imouaddine/Stylejonction#11]
Hi Imad,

I downloaded the code today and many of the tests were broken, I tried hard to fix some of them but I'm not sure whatis going on there. Right now some of the integration tests are failing, because of something in this commit: https://github.com/imouaddine/Stylejonction/commit/3fa15a84962143b21af094353ee65a6b2b001ff9  I'm leaving it for now because your message states that there's some work left there, so maybe you now what is going on.

**Comment by imouaddine** [comment]
Yeah no problem, I was aware there are some failing tests but I prefered to commit to facilitate the merging specially I
ve added many changes.

**Comment by ignacy** [comment]
I have done some more research on this. Commenting out line 20 of portfolios_controller.coffee "@add_preview", makes the integration test pass. So the problem is somwhere in the preview, related to missing cover. Integration tests are very fragile, especially when it comes to markup/js.

I have nothing against commiting work in progress, but it would be great if you could mark the tests that are failing after your work. When I start my work I do:

```
git pull
rake db:migrate:reset && rake db:test:prepare && rake db:seed && rake test
```

To make sure I'm starting with a clean slate.
When I finish I do the same

```
rake db:migrate:reset && rake db:test:prepare && rake db:seed && rake test
git push origin master
```

This way I'm sure that I did't brake anything. When I pull something with broken code I'm not sure wheter your changes broke something or did mine changes do it (I work on different machines). So what I have to do is manually checkout each git revision and find the place where the tests start failing. That's why I would greatly appriciate if you could add flunk() to tests you broke (http://www.ensta-paristech.fr/~diam/ruby/online/ruby-doc-stdlib/libdoc/test/unit/rdoc/classes/Test/Unit/Assertions.html#M004518). If you do 

```
 flunk "This is still work in progress"
```

I will know right away that it's ok that this test is failing.

**Comment by imouaddine** [comment]
Sorry Ignacy, I'm still adapting to the rails workflow.  Next time I will use flunk or ideally I will not commit my code until all the test are passed because what you've said makes sense.

**Comment by imouaddine** [comment]
Let me fix this issue I will commit once all the tests are passed.
