### ISSUE TITLE
Add the ability to specify a default project

### ISSUE THREAD

**Issue by imouaddine** [imouaddine/Stylejonction#4]
The first created project is by default the default project of the portfolio.

Portfolio will have as cover the one's of the default project.

>  Hi Imad,
> 
>  I need some more info here. What's a default project? And is it specified automatically when portfolio is created?
> 
> Thanks,
> Ignacy

**Comment by ignacy** [comment]
Do we default project for user, when the user is created?

**Comment by imouaddine** [comment]
I want to stress that after creation of a new user, no project is created by default. I was mistaken about that when I told you to do it.

If the user creates his first project, it will be the default one.

if the user select a project as default one, do not forget to uncheck the others.

If the user don't have any default project, in the public portfolio we will consider the first one created as the default one.

**Comment by ignacy** [comment]
OK thank you for clarifying, I will fix it right away.
